import type { FlowDefinition } from '../types';

export interface FlowTemplate {
  id: string;
  name: string;
  description: string;
  category: 'General' | 'Support' | 'Sales' | 'Marketing' | 'AI & Automation';
  badge?: string;
  icon: string;
  suggestedFlowName: string;
  definition: FlowDefinition;
  tags: string[];
}

export const FLOW_TEMPLATES: FlowTemplate[] = [
  {
    id: 'blank',
    name: 'Blank Flow',
    description: 'Start with a fresh, empty canvas to build your customized workflow from scratch.',
    category: 'General',
    badge: 'Empty Canvas',
    icon: 'FileCode',
    suggestedFlowName: 'New Custom Flow',
    tags: ['Custom', 'Clean Canvas', 'Flexible'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: '👋 Hello! How can we assist you today?',
          position: { x: 250, y: 100 },
        },
      ],
      edges: [],
    },
  },
  {
    id: 'welcome-onboarding',
    name: 'Welcome & Onboarding',
    description: 'Warmly welcome new contacts, ask for their name, personalize responses with variables, and route them to their area of interest.',
    category: 'Marketing',
    badge: 'Popular',
    icon: 'Sparkles',
    suggestedFlowName: 'Customer Welcome & Onboarding',
    tags: ['Welcome', 'Capture Name', 'Branching'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: '👋 Welcome to our service! We are delighted to have you here.',
          next: 'node_2',
          position: { x: 250, y: 50 },
        },
        {
          id: 'node_2',
          type: 'input',
          prompt: 'May I know your full name?',
          saveAs: 'userName',
          next: 'node_3',
          position: { x: 250, y: 200 },
        },
        {
          id: 'node_3',
          type: 'message',
          text: 'Delighted to meet you, {{userName}}! What brings you to us today?\n\n1️⃣ Explore Products & Features\n2️⃣ Pricing & Packages\n3️⃣ Talk to Support Specialist',
          next: 'node_4',
          position: { x: 250, y: 370 },
        },
        {
          id: 'node_4',
          type: 'input',
          prompt: 'Please reply with 1, 2, or 3:',
          saveAs: 'userChoice',
          next: 'node_5',
          position: { x: 250, y: 540 },
        },
        {
          id: 'node_5',
          type: 'condition',
          variable: 'userChoice',
          branches: [
            { equals: '1', next: 'node_6' },
            { equals: '2', next: 'node_7' },
            { equals: '3', next: 'node_8' },
          ],
          default: 'node_6',
          position: { x: 250, y: 700 },
        },
        {
          id: 'node_6',
          type: 'message',
          text: '🚀 You can explore our full product catalog and features anytime right here in this chat.',
          next: 'node_9',
          position: { x: 50, y: 900 },
        },
        {
          id: 'node_7',
          type: 'message',
          text: '💰 Our plans start from Basic ($29/mo) to Pro ($99/mo). Reply anytime if you want a personalized quote!',
          next: 'node_9',
          position: { x: 250, y: 900 },
        },
        {
          id: 'node_8',
          type: 'handoff',
          position: { x: 480, y: 900 },
        },
        {
          id: 'node_9',
          type: 'end',
          position: { x: 150, y: 1060 },
        },
      ],
      edges: [
        { id: 'e_1_2', source: 'node_1', sourceHandle: 'continue', target: 'node_2' },
        { id: 'e_2_3', source: 'node_2', sourceHandle: 'continue', target: 'node_3' },
        { id: 'e_3_4', source: 'node_3', sourceHandle: 'continue', target: 'node_4' },
        { id: 'e_4_5', source: 'node_4', sourceHandle: 'continue', target: 'node_5' },
        { id: 'e_5_6', source: 'node_5', sourceHandle: 'branch_0', target: 'node_6', label: '1' },
        { id: 'e_5_7', source: 'node_5', sourceHandle: 'branch_1', target: 'node_7', label: '2' },
        { id: 'e_5_8', source: 'node_5', sourceHandle: 'branch_2', target: 'node_8', label: '3' },
        { id: 'e_6_9', source: 'node_6', sourceHandle: 'continue', target: 'node_9' },
        { id: 'e_7_9', source: 'node_7', sourceHandle: 'continue', target: 'node_9' },
      ],
    },
  },
  {
    id: 'faq-bot',
    name: 'FAQ & Self-Service Menu',
    description: 'Instant self-service support bot answering frequent questions about business hours, delivery, refunds, and live agent requests.',
    category: 'Support',
    badge: 'Recommended',
    icon: 'HelpCircle',
    suggestedFlowName: 'FAQ & Self-Service Bot',
    tags: ['Customer Support', 'FAQ', 'Self-Service'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: '🤖 Hi! Welcome to our 24/7 Automated Support Menu. How can we help you today?\n\n1️⃣ Business Hours & Location\n2️⃣ Shipping & Delivery Time\n3️⃣ Refund & Return Policy\n4️⃣ Speak with Human Agent',
          next: 'node_2',
          position: { x: 250, y: 50 },
        },
        {
          id: 'node_2',
          type: 'input',
          prompt: 'Please type 1, 2, 3, or 4:',
          saveAs: 'faqSelection',
          next: 'node_3',
          position: { x: 250, y: 230 },
        },
        {
          id: 'node_3',
          type: 'condition',
          variable: 'faqSelection',
          branches: [
            { equals: '1', next: 'node_4' },
            { equals: '2', next: 'node_5' },
            { equals: '3', next: 'node_6' },
            { equals: '4', next: 'node_7' },
          ],
          default: 'node_8',
          position: { x: 250, y: 400 },
        },
        {
          id: 'node_4',
          type: 'message',
          text: '📍 We are located at 100 Innovation Blvd. Open Monday through Friday from 9:00 AM to 6:00 PM EST.',
          next: 'node_9',
          position: { x: 0, y: 600 },
        },
        {
          id: 'node_5',
          type: 'message',
          text: '📦 Standard domestic shipping takes 2-4 business days. Express next-day shipping is also available at checkout.',
          next: 'node_9',
          position: { x: 200, y: 600 },
        },
        {
          id: 'node_6',
          type: 'message',
          text: '💳 We offer a 30-day money-back guarantee for all unused items in their original packaging.',
          next: 'node_9',
          position: { x: 400, y: 600 },
        },
        {
          id: 'node_7',
          type: 'handoff',
          position: { x: 600, y: 600 },
        },
        {
          id: 'node_8',
          type: 'message',
          text: 'I didn\'t quite recognize that option. Let me connect you directly to a member of our team!',
          next: 'node_7',
          position: { x: 750, y: 450 },
        },
        {
          id: 'node_9',
          type: 'message',
          text: 'Did this resolve your inquiry? Type any question to start over, or an agent will follow up if needed.',
          next: 'node_10',
          position: { x: 200, y: 780 },
        },
        {
          id: 'node_10',
          type: 'end',
          position: { x: 200, y: 940 },
        },
      ],
      edges: [
        { id: 'e_1_2', source: 'node_1', sourceHandle: 'continue', target: 'node_2' },
        { id: 'e_2_3', source: 'node_2', sourceHandle: 'continue', target: 'node_3' },
        { id: 'e_3_4', source: 'node_3', sourceHandle: 'branch_0', target: 'node_4', label: '1' },
        { id: 'e_3_5', source: 'node_3', sourceHandle: 'branch_1', target: 'node_5', label: '2' },
        { id: 'e_3_6', source: 'node_3', sourceHandle: 'branch_2', target: 'node_6', label: '3' },
        { id: 'e_3_7', source: 'node_3', sourceHandle: 'branch_3', target: 'node_7', label: '4' },
        { id: 'e_3_8', source: 'node_3', sourceHandle: 'default', target: 'node_8', label: 'Other' },
        { id: 'e_8_7', source: 'node_8', sourceHandle: 'continue', target: 'node_7' },
        { id: 'e_4_9', source: 'node_4', sourceHandle: 'continue', target: 'node_9' },
        { id: 'e_5_9', source: 'node_5', sourceHandle: 'continue', target: 'node_9' },
        { id: 'e_6_9', source: 'node_6', sourceHandle: 'continue', target: 'node_9' },
        { id: 'e_9_10', source: 'node_9', sourceHandle: 'continue', target: 'node_10' },
      ],
    },
  },
  {
    id: 'customer-followup',
    name: 'Customer Follow-Up & CSAT Survey',
    description: 'Post-service follow-up using BullMQ Redis delay timer queue to check in and collect 1-5 star CSAT feedback.',
    category: 'Support',
    badge: 'Delayed Queue',
    icon: 'Clock',
    suggestedFlowName: 'Post-Resolution CSAT Survey',
    tags: ['Feedback', 'BullMQ Queue', 'CSAT Survey'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: 'Thank you for reaching out today! We hope our team was able to assist you with everything you needed.',
          next: 'node_2',
          position: { x: 250, y: 50 },
        },
        {
          id: 'node_2',
          type: 'wait',
          duration: 2,
          durationUnit: 'hours',
          next: 'node_3',
          position: { x: 250, y: 200 },
        },
        {
          id: 'node_3',
          type: 'input',
          prompt: '⭐ On a scale of 1 to 5 (5 being Excellent), how satisfied were you with our service today?',
          saveAs: 'csatScore',
          next: 'node_4',
          position: { x: 250, y: 370 },
        },
        {
          id: 'node_4',
          type: 'condition',
          variable: 'csatScore',
          branches: [
            { equals: '5', next: 'node_5' },
            { equals: '4', next: 'node_5' },
            { equals: '3', next: 'node_6' },
            { equals: '2', next: 'node_6' },
            { equals: '1', next: 'node_6' },
          ],
          default: 'node_5',
          position: { x: 250, y: 540 },
        },
        {
          id: 'node_5',
          type: 'message',
          text: '🎉 Thank you so much for the glowing review! We truly appreciate having you as our customer.',
          next: 'node_7',
          position: { x: 100, y: 740 },
        },
        {
          id: 'node_6',
          type: 'message',
          text: 'We are sorry your experience was not perfect. A customer relations manager will review your ticket to make things right.',
          next: 'node_8',
          position: { x: 420, y: 740 },
        },
        {
          id: 'node_7',
          type: 'end',
          position: { x: 100, y: 900 },
        },
        {
          id: 'node_8',
          type: 'handoff',
          position: { x: 420, y: 900 },
        },
      ],
      edges: [
        { id: 'e_1_2', source: 'node_1', sourceHandle: 'continue', target: 'node_2' },
        { id: 'e_2_3', source: 'node_2', sourceHandle: 'continue', target: 'node_3' },
        { id: 'e_3_4', source: 'node_3', sourceHandle: 'continue', target: 'node_4' },
        { id: 'e_4_5a', source: 'node_4', sourceHandle: 'branch_0', target: 'node_5', label: '5' },
        { id: 'e_4_5b', source: 'node_4', sourceHandle: 'branch_1', target: 'node_5', label: '4' },
        { id: 'e_4_6a', source: 'node_4', sourceHandle: 'branch_2', target: 'node_6', label: '3' },
        { id: 'e_4_6b', source: 'node_4', sourceHandle: 'branch_3', target: 'node_6', label: '2' },
        { id: 'e_4_6c', source: 'node_4', sourceHandle: 'branch_4', target: 'node_6', label: '1' },
        { id: 'e_5_7', source: 'node_5', sourceHandle: 'continue', target: 'node_7' },
        { id: 'e_6_8', source: 'node_6', sourceHandle: 'continue', target: 'node_8' },
      ],
    },
  },
  {
    id: 'lead-qualification',
    name: 'Lead Qualification & Discovery',
    description: 'Capture company details, team size, and requirements to automatically route high-value enterprise leads to sales representatives.',
    category: 'Sales',
    badge: 'B2B Sales',
    icon: 'GitBranch',
    suggestedFlowName: 'B2B Lead Qualification Flow',
    tags: ['Sales', 'Lead Capture', 'Enterprise Routing'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: '💼 Welcome! Let us help find the ideal solution for your organization.',
          next: 'node_2',
          position: { x: 250, y: 50 },
        },
        {
          id: 'node_2',
          type: 'input',
          prompt: 'What is your company or organization name?',
          saveAs: 'companyName',
          next: 'node_3',
          position: { x: 250, y: 200 },
        },
        {
          id: 'node_3',
          type: 'input',
          prompt: 'How many team members or agents will be using the platform? (e.g. 1-10, 10-50, 50+)',
          saveAs: 'teamSize',
          next: 'node_4',
          position: { x: 250, y: 370 },
        },
        {
          id: 'node_4',
          type: 'condition',
          variable: 'teamSize',
          branches: [
            { equals: '50+', next: 'node_5' },
            { equals: '10-50', next: 'node_5' },
          ],
          default: 'node_6',
          position: { x: 250, y: 540 },
        },
        {
          id: 'node_5',
          type: 'message',
          text: '🌟 Excellent! For enterprise requirements at {{companyName}}, we assign a dedicated solutions engineer to assist you right away.',
          next: 'node_7',
          position: { x: 100, y: 720 },
        },
        {
          id: 'node_6',
          type: 'message',
          text: '👍 Great! You qualify for our instant self-service onboarding with full feature access and a 14-day free trial.',
          next: 'node_8',
          position: { x: 420, y: 720 },
        },
        {
          id: 'node_7',
          type: 'handoff',
          position: { x: 100, y: 880 },
        },
        {
          id: 'node_8',
          type: 'end',
          position: { x: 420, y: 880 },
        },
      ],
      edges: [
        { id: 'e_1_2', source: 'node_1', sourceHandle: 'continue', target: 'node_2' },
        { id: 'e_2_3', source: 'node_2', sourceHandle: 'continue', target: 'node_3' },
        { id: 'e_3_4', source: 'node_3', sourceHandle: 'continue', target: 'node_4' },
        { id: 'e_4_5a', source: 'node_4', sourceHandle: 'branch_0', target: 'node_5', label: '50+' },
        { id: 'e_4_5b', source: 'node_4', sourceHandle: 'branch_1', target: 'node_5', label: '10-50' },
        { id: 'e_4_6', source: 'node_4', sourceHandle: 'default', target: 'node_6', label: 'Other' },
        { id: 'e_5_7', source: 'node_5', sourceHandle: 'continue', target: 'node_7' },
        { id: 'e_6_8', source: 'node_6', sourceHandle: 'continue', target: 'node_8' },
      ],
    },
  },
  {
    id: 'ai-kb-support',
    name: 'AI Knowledge Base Support (RAG)',
    description: 'Autonomous AI assistant connected to your Vector Knowledge Base with dynamic similarity score threshold and human agent handoff.',
    category: 'AI & Automation',
    badge: 'RAG AI',
    icon: 'Brain',
    suggestedFlowName: 'Autonomous AI Support Flow',
    tags: ['AI Agent', 'Vector RAG', 'Smart Fallback'],
    definition: {
      entryNodeId: 'node_1',
      nodes: [
        {
          id: 'node_1',
          type: 'message',
          text: '🤖 Hello! I am your AI Knowledge Assistant. You can ask me any question regarding our services, docs, or policies.',
          next: 'node_2',
          position: { x: 250, y: 50 },
        },
        {
          id: 'node_2',
          type: 'input',
          prompt: 'What question can I answer for you today?',
          saveAs: 'userQuestion',
          next: 'node_3',
          position: { x: 250, y: 200 },
        },
        {
          id: 'node_3',
          type: 'ai_agent',
          knowledgeBaseId: '',
          queryVariable: 'userQuestion',
          saveResponseAs: 'aiResponse',
          sendImmediately: true,
          fallbackThreshold: 0.35,
          onFallback: 'node_5',
          next: 'node_4',
          position: { x: 250, y: 380 },
        },
        {
          id: 'node_4',
          type: 'message',
          text: 'Is there anything else I can clarify for you? Feel free to ask another question at any time!',
          next: 'node_6',
          position: { x: 100, y: 600 },
        },
        {
          id: 'node_5',
          type: 'message',
          text: 'I want to ensure you receive the most accurate response. Let me transfer you directly to a human support agent.',
          next: 'node_7',
          position: { x: 420, y: 600 },
        },
        {
          id: 'node_6',
          type: 'end',
          position: { x: 100, y: 760 },
        },
        {
          id: 'node_7',
          type: 'handoff',
          position: { x: 420, y: 760 },
        },
      ],
      edges: [
        { id: 'e_1_2', source: 'node_1', sourceHandle: 'continue', target: 'node_2' },
        { id: 'e_2_3', source: 'node_2', sourceHandle: 'continue', target: 'node_3' },
        { id: 'e_3_4', source: 'node_3', sourceHandle: 'continue', target: 'node_4', label: 'Answered' },
        { id: 'e_3_5', source: 'node_3', sourceHandle: 'fallback', target: 'node_5', label: 'Low Confidence' },
        { id: 'e_4_6', source: 'node_4', sourceHandle: 'continue', target: 'node_6' },
        { id: 'e_5_7', source: 'node_5', sourceHandle: 'continue', target: 'node_7' },
      ],
    },
  },
];
